import sys
from PyQt5 import QtCore, QtWidgets
from makepred import predict_new_data
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window1 = QtWidgets.QWidget()
    window1.setGeometry(500, 250, 800, 600)
    window1.setFixedSize(800, 600)
    window1.setWindowTitle('Prediction Tool')
    window1.setStyleSheet('background-color:beige')
    frame = QtWidgets.QFrame(window1)
    frame.setFrameShape(frame.StyledPanel)
    frame.setGeometry(50, 50, 700, 500)
    frame.setStyleSheet('background-color:rgb(137, 207, 240);border: 1px solid black;border-radius:10px;')
    lbl1 = QtWidgets.QLabel("House Pricing Prediction", window1)
    lbl1.setGeometry(130, 60, 560, 60)
    lbl1.setStyleSheet('background-color:rgb(137, 207, 240); font-color:black;font-size:50px;')
    lbl2 = QtWidgets.QLabel("Number of Rooms : ", window1)
    lbl2.setGeometry(75, 160, 200, 30)
    lbl2.setStyleSheet('background-color:rgb(137, 207, 240); font-color:black;font-size:20px;')
    lbl3 = QtWidgets.QLabel("Lower Status of The Population : ", window1)
    lbl3.setGeometry(75, 260, 400, 30)
    lbl3.setStyleSheet('background-color:rgb(137, 207, 240); font-color:black;font-size:20px;')
    lbl4 = QtWidgets.QLabel("Student to Teacher Ratio : ", window1)
    lbl4.setGeometry(75, 360, 400, 30)
    lbl4.setStyleSheet('background-color:rgb(137, 207, 240); font-color:black;font-size:20px;')
    combo_rooms = QtWidgets.QComboBox(window1)
    combo_rooms.setGeometry(450, 160, 250, 30)
    combo_rooms.addItems(["3", "4", "5", "6", "7"])
    combo_population = QtWidgets.QComboBox(window1)
    combo_population.setGeometry(450, 260, 250, 30)
    combo_population.addItems(["low", "medium", "high", "extreme"])
    combo_ratio = QtWidgets.QComboBox(window1)
    combo_ratio.setGeometry(450, 360, 250, 30)
    combo_ratio.addItems(["low", "medium", "high", "extreme"])
    pred_lbl = QtWidgets.QLabel("", window1)
    pred_lbl.setGeometry(320, 510, 200, 40)
    pred_lbl.setStyleSheet('background-color:black;font-size:30px;font-weight:bold;color:white;')
    pred_lbl.setAlignment(QtCore.Qt.AlignCenter)
    def on_predict():
        rooms_number = int(combo_rooms.currentText())
        pop = combo_population.currentText()
        ratio = combo_ratio.currentText()
        predicted_price = predict_new_data(rooms_number, pop, ratio)
        pred_lbl.setText(f"${predicted_price:,.2f}")
    btn = QtWidgets.QPushButton('Predict Price', window1)
    btn.setGeometry(320, 420, 180, 60)
    btn.setStyleSheet('background-color:black;color:red;border:2px black;border-radius:20px')
    btn.clicked.connect(on_predict)
    window1.show()
    app.exec_()