import pandas as pd
sal = pd.read_csv("C:\D\Amit\Advanced_machine_learning_amit\materials\Python_for_ml\session\Salaries.csv")
print(sal.head())
print("*"*60)
print(sal.tail())
print("*"*60)
print(sal.info())
print("*"*60)
print("OBJECT")
print(sal['BasePay'])
print("#"*60)
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')
sal['OvertimePay'] = pd.to_numeric(sal['OvertimePay'], errors='coerce')
print("NUMERICAL")
print(sal['BasePay'])
print("*"*60)
print(sal['OvertimePay'].max())
print("*"*60)
print(sal[sal['EmployeeName']== 'JOSEPH DRISCOLL']['JobTitle'])